name: hardware_definition_app
description: HardwareDefinition App

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_wordpress: ^0.1.4
  loading: ^1.0.1
  font_awesome_flutter: ^8.5.0
  flutter_svg: ^0.14.1
  pull_to_refresh: ^1.5.6


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  fonts:
    - family: coolvetica
      fonts:
        - asset: fonts/coolvetica rg.ttf
    - family: quicksand
      fonts:
        - asset: fonts/Quicksand/Quicksand-Regular.ttf
    - family: muli
      fonts:
        - asset: fonts/Muli/Muli-Light.ttf
    - family: muli
      fonts:
        - asset: fonts/Barlow/Barlow-Bold.ttf
  uses-material-design: true
  assets:
    - assets/

